blank_issues_enabled: false
contact_links:
  - name: Support Forum
    url: https://www.reddit.com/r/uBlockOrigin/
    about: For support, questions, or help, visit /r/uBlockOrigin.
  - name: Filter List Issues / Website Problems
    url: https://github.com/uBlockOrigin/uAssets/issues
    about: Report issues with filter lists or broken website functionality in the uAssets issue tracker.
  - name: uBO Lite (uBOL) Issues
    url: https://github.com/uBlockOrigin/uBOL-home/issues
    about: Report issues specific to the Manifest Version 3 (MV3) variant in the uBOL issue tracker.
  - name: Filter List Issues
    url: https://github.com/uBlockOrigin/uBlock-issues#filter-list-issues
    about: New filter list requests are not permitted and will be declined and closed.
